### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by ghost** [rachelproject/rachelpiOS#4]
@mattneel 

from a straight install of raspbian jessie, not much happens when running:

```
curl https://github.com/mattneel/rachelpios/tree/master/rachel.py | python
```

![image](https://cloud.githubusercontent.com/assets/9270352/11459639/ded48294-968f-11e5-8988-a42d116f4313.png)

Can we shift items from the /mattneed/ subdomain to rachelproject?

Thank you!

**Comment by spatiald** [comment]
I think your code should be:

curl -fsS https://raw.githubusercontent.com/mattneel/rachelpiOS/master/installer.py | python

**Comment by mattneel** [comment]
Pull in the latest request, and he is correct.

**Comment by j-schwartz** [comment]
Hi Team -

Trying to find a place to track some changes we can make to the script.  I'm 100% aware these are mostly my fault in setting up the base package here, so just trying to keep track of things.
- No opportunity to enter a username w/ KA-Lite.  Currently uses 'root' by default, would like to use 'pi'
- hostname should be rachel instead of raspberrypi
- password for device should be rachel instead of raspberrypi
  ![image](https://cloud.githubusercontent.com/assets/9270388/11519344/4744af6a-984e-11e5-8e76-3d59d0204e7c.png)
- KA-Lite installs fine as 'pi' if running post install script
  `kalite manage setup`

-contentshell (if this is being pulled in) does not have an existing 'modules' directory in /var/www

**Comment by mattneel** [comment]
I've created a Trello org and board where we can track these better.
https://trello.com/rachel63615082

Let me know your Trello logins and I'll add you to the org. I think I can transfer ownership to you as well Jeremy.

**Comment by ghost** [comment]
jeremy@worldpossible.org

**Comment by mattneel** [comment]
Alright. Added and gave you admin.

**Comment by spatiald** [comment]
sam@hackersforcharity.org

**Comment by ghost** [comment]
Hi team,

Jfield or Matt - it looks like we have a 'html' folder within /var/www/
that now contains modules.  Is this on purpose by either of you?  Totally
fine, but I started to change this in the script and wasn't sure if I
shouldn't.

We used to drop all of the contentshell straight into /var/www/ and now
it's going into /var/www/html.

Thanks,
Jeremy

**Comment by mattneel** [comment]
Wherever you want them to go is fine, just make sure to edit the files/default Apache2 config to match the location if you make the change to the script.

**Comment by ghost** [comment]
Are you talking about on Rachel or on dev.worldpossible.org - I may have
reorganized things on the second machine a few weeks ago.

**Comment by ghost** [comment]
On rachelpi.  I think it was a script thing with me and Matt not a content
shell thing.  I think we can consider the issue mute at this point.

**Comment by needlestack** [comment]
Not sure if there's any open issue here still - can we close this?

**Comment by needlestack** [comment]
Closing - if there's anything unresolved above, just open a new issue.
