### ISSUE TITLE
KA-Lite not booting at start

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelpiOS#6]
somewhere in the setup process, KA-lite should offer an option to boot at start.  May be a KA-Lite issue.

**Comment by edresor** [comment]
Can you start KA-Lite manually?
Does the start up script run the command: kalite start  from the correct directory?
I ran kalite manage help setup and did not see any option in setup autostart.

**Comment by needlestack** [comment]
It looks like it with the latest version of the build script kalite is starting automatically for me. Re-open if you run into this again.

Actually, upon reflection, I think this may be because kalite was starting so slowly (10 minutes or more after boot) and during that time `kalite status` indicates it didn't start. But if you run `top` you'll see a python2 process chugging away -- that's kalite.

Hopefully the new caching-enabled version will eliminate this - though on the initial startup after installation you will have the same delay.
